import { DeepPartial } from 'typeorm';
import { TLancamentoOutput } from '../entity/lancamento.entity';
import { LancamentoStatus } from '../enum/lancamento-status.enum';

export const LancamaentoOutputExample: DeepPartial<TLancamentoOutput>[] = [
  {
    ocorrencias: [],
    historico: [
      {
        id: 2,
        valor: 1.01,
        data_ordem: '2024-06-10T17:21:35.890Z',
        data_pgto: null,
        data_lancamento: '2024-06-10T17:21:35.890Z',
        algoritmo: 10.06,
        glosa: -20.01,
        recurso: 30,
        anexo: 40.01,
        numero_processo: '0130',
        is_autorizado: false,
        is_pago: false,
        status: LancamentoStatus._1_gerado,
        motivo_cancelamento: null,
        createdAt: '2024-09-20T19:59:11.167Z',
        updatedAt: '2024-09-21T02:11:50.271Z',
        backupAt: '2024-09-21T02:24:02.720Z',
        autorizado_por: [],
      },
    ],
    id: 3,
    valor: 1.99,
    data_ordem: '2024-05-10T17:21:35.890Z',
    data_pgto: null,
    data_lancamento: '2024-05-10T17:21:35.890Z',
    algoritmo: 10.99,
    glosa: -20.99,
    recurso: 30.99,
    anexo: 40.99,
    numero_processo: '0123',
    is_autorizado: false,
    is_pago: false,
    status: LancamentoStatus._2_autorizado_parcial,
    motivo_cancelamento: null,
    createdAt: '2024-09-20T19:59:11.167Z',
    updatedAt: '2024-09-22T05:31:37.703Z',
    deletedAt: null,
    autorizado_por: [
      {
        id: 1726,
        nome: 'João da silva',
        data_autorizacao: new Date('2024-09-22T05:31:37.703Z'),
      },
    ],
    autor: {
      id: 1726,
      fullName: null,
    },
    clienteFavorecido: {
      id: 5,
      nome: 'CONSORCIO SANTA CRUZ TRANSPORTES',
    },
    autorizacoes: [
      {
        aux_bank: null,
        aux_inviteStatus: null,
        id: 1726,
        fullName: null,
        permitCode: null as unknown as string,
        cpfCnpj: null as unknown as string,
        bankCode: null as unknown as number,
        bankAgency: null as unknown as string,
        bankAccount: null as unknown as string,
        bankAccountDigit: null as unknown as string,
        phone: null as unknown as string,
        isSgtuBlocked: null as unknown as boolean,
        passValidatorId: null as unknown as string,
        aux_isRegistrationComplete: false,
        aux_missingRegistrationFields: ['cpfCnpj', 'permitCode', 'passValidatorId', 'phone', 'bankCode', 'bankAgency', 'bankAccount', 'bankAccountDigit'],
      },
    ],
  },
];
