export enum Cnab104TipoServico {
  Optantes = '00',
  DebitosRecebimento = '05',
  PagamentoDividendos = '10',
  PagamentoFornecedor = '20',
  PagamentoTributos = '22',
  PagamentoSalarios = '30',
  PagamentoSinistrosSegurados = '50',
  PagamentoDespesasViajanteTransito = '60',
  PagamentoAutorizado = '70',
  PagamentoCredenciados = '75',
  PagamentoRepresentantesVendedoresAutorizados = '80',
  PagamentoBeneficios = '90',
  PagamentoDiversos = '98',
}
