import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateCnabExtrato1711051116551 implements MigrationInterface {
    name = 'CreateCnabExtrato1711051116551'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_dc18daa696860586ba4667a9d31"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c28e52f758e7bbc53828db92194"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_75e2be4ce11d447ef43be0e374f"`);
        await queryRunner.query(`ALTER TABLE "lancamento" DROP CONSTRAINT "FK_ea066846cf244204c813b72ff50"`);
        await queryRunner.query(`ALTER TABLE "lancamento" DROP CONSTRAINT "FK_80f6744ced95ab9e8dd0b212fee"`);
        await queryRunner.query(`ALTER TABLE "transacao" DROP CONSTRAINT "FK_097c8d865615a7ec0516929b65f"`);
        await queryRunner.query(`ALTER TABLE "header_arquivo" DROP CONSTRAINT "FK_2ecc2606a7de054a63c0e22f206"`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" DROP CONSTRAINT "FK_9034ea1202b6574b75a2304d419"`);
        await queryRunner.query(`ALTER TABLE "forgot" DROP CONSTRAINT "FK_31f3c80de0525250f31e23a9b83"`);
        await queryRunner.query(`ALTER TABLE "invite" DROP CONSTRAINT "FK_118ec7f671543d9b992512e7cb9"`);
        await queryRunner.query(`ALTER TABLE "invite" DROP CONSTRAINT "FK_91bfeec7a9574f458e5b592472d"`);
        await queryRunner.query(`ALTER TABLE "setting" DROP CONSTRAINT "FK_a5bc5fbecc0b218be61ef25b725"`);
        await queryRunner.query(`ALTER TABLE "header_lote" DROP CONSTRAINT "FK_75f6c2ed71c10935915157b45f9"`);
        await queryRunner.query(`ALTER TABLE "header_lote" DROP CONSTRAINT "FK_cd9a79df522dbe1b057230614e9"`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" DROP CONSTRAINT "FK_b5a7c03d9250881766627229e5d"`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" DROP CONSTRAINT "FK_7228a16907c82f80e733dcb465b"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP CONSTRAINT "FK_67142ca27ead7b1bccbbc968c4b"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP CONSTRAINT "FK_04f9231ba148125f267dd160196"`);
        await queryRunner.query(`ALTER TABLE "detalhe_b" DROP CONSTRAINT "FK_2c8fd111d9b6ad8e653cdbf725f"`);
        await queryRunner.query(`CREATE TABLE "permissionario_role" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_PermissionarioRole_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transacao_status" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_TransacaoStatus_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "extrato_header_arquivo" ("id" SERIAL NOT NULL, "tipoArquivo" integer, "codigoBanco" character varying(10), "tipoInscricao" character varying(2), "numeroInscricao" character varying(14), "codigoConvenio" character varying(6), "parametroTransmissao" character varying(2), "agencia" character varying(5), "dvAgencia" character varying(1), "numeroConta" character varying(12), "dvConta" character varying(1), "nomeEmpresa" character varying(100), "dataGeracao" TIMESTAMP, "horaGeracao" TIME, "nsa" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ExtratoHeaderArquivo_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "extrato_header_lote" ("id" SERIAL NOT NULL, "loteServico" integer, "tipoInscricao" character varying, "numeroInscricao" character varying, "codigoConvenioBanco" character varying, "tipoCompromisso" character varying, "parametroTransmissao" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "extratoHeaderArquivoId" integer, CONSTRAINT "PK_ExtratoHeaderLote_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "extrato_detalhe_e" ("id" SERIAL NOT NULL, "loteServico" integer NOT NULL, "tipoInscricao" integer NOT NULL, "numeroInscricao" character varying NOT NULL, "codigoConvenioBanco" character varying NOT NULL, "agencia" character varying NOT NULL, "dvAgencia" character varying NOT NULL, "conta" character varying NOT NULL, "dvConta" character varying NOT NULL, "dvAgenciaConta" character varying NOT NULL, "nomeEmpresa" character varying NOT NULL, "naturezaLancamento" character varying NOT NULL, "tipoComplementoLancamento" character varying NOT NULL, "complementoLancamento" character varying NOT NULL, "isencaoCpmf" character varying NOT NULL, "dataContabil" TIMESTAMP NOT NULL, "dataLancamento" TIMESTAMP NOT NULL, "valorLancamento" numeric(5,2), "tipoLancamento" character varying NOT NULL, "categoriaLancamento" character varying NOT NULL, "codigoHistoricoBanco" character varying NOT NULL, "descricaoHistoricoBanco" character varying NOT NULL, "numeroDocumento" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "extratoHeaderLoteId" integer, CONSTRAINT "PK_ExtratoDetalheE_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "item_transacao_status" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_ItemTransacaoStatusId_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" DROP COLUMN "dtVencimento"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "permissionarioRoleId" integer`);
        await queryRunner.query(`ALTER TABLE "cliente_favorecido" ADD "permissionarioRoleId" integer`);
        await queryRunner.query(`ALTER TABLE "cliente_favorecido" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "cliente_favorecido" ADD CONSTRAINT "UQ_0d5a5a996843f1f5e3f0e5ca380" UNIQUE ("userId")`);
        await queryRunner.query(`ALTER TABLE "lancamento" ADD "data_lancamento" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transacao" ADD "idOperadora" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transacao" ADD "idConsorcio" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transacao" ADD "versaoOrdemPagamento" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transacao" ADD "statusId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" ADD "dataVencimento" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" ADD "idDetalheARetorno" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "header_lote" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD "nomeOperadora" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD "dataOrdem" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD "versaoOrdemPagamento" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD "detalheAId" integer`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD CONSTRAINT "UQ_611a02b09938bef0bc91cc85e86" UNIQUE ("detalheAId")`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD "statusId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "detalhe_b" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transacao" ALTER COLUMN "servico" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transacao" ALTER COLUMN "valorRateioCredito" TYPE numeric(10,3)`);
        await queryRunner.query(`ALTER TABLE "transacao" ALTER COLUMN "valorRateioDebito" TYPE numeric(10,3)`);
        await queryRunner.query(`ALTER TABLE "transacao" DROP COLUMN "quantidadeTotalTransacao"`);
        await queryRunner.query(`ALTER TABLE "transacao" ADD "quantidadeTotalTransacao" integer`);
        await queryRunner.query(`ALTER TABLE "transacao" DROP COLUMN "valorTotalTransacaoBruto"`);
        await queryRunner.query(`ALTER TABLE "transacao" ADD "valorTotalTransacaoBruto" numeric(10,3)`);
        await queryRunner.query(`ALTER TABLE "transacao" ALTER COLUMN "valorDescontoTaxa" TYPE numeric(10,3)`);
        await queryRunner.query(`ALTER TABLE "transacao" ALTER COLUMN "valorTotalTransacaoLiquido" TYPE numeric(10,3)`);
        await queryRunner.query(`ALTER TABLE "transacao" ALTER COLUMN "valorTotalTransacaoCaptura" TYPE numeric(10,3)`);
        await queryRunner.query(`ALTER TABLE "header_arquivo" DROP COLUMN "dataGeracao"`);
        await queryRunner.query(`ALTER TABLE "header_arquivo" ADD "dataGeracao" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "header_lote" DROP COLUMN "loteServico"`);
        await queryRunner.query(`ALTER TABLE "header_lote" ADD "loteServico" integer`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" DROP COLUMN "quantidadeMoeda"`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" ADD "quantidadeMoeda" numeric(5,10)`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_User_photo_ManyToOne" FOREIGN KEY ("photoId") REFERENCES "file"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_User_role_ManyToOne" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_User_status_ManyToOne" FOREIGN KEY ("statusId") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_User_permissionarioRole_ManyToOne" FOREIGN KEY ("permissionarioRoleId") REFERENCES "permissionario_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cliente_favorecido" ADD CONSTRAINT "FK_ClienteFavorecido_permissionarioRole_ManyToOne" FOREIGN KEY ("permissionarioRoleId") REFERENCES "permissionario_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cliente_favorecido" ADD CONSTRAINT "FK_ClienteFavorecido_user_OneToOne" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lancamento" ADD CONSTRAINT "FK_Lancamento_user_ManyToOne" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lancamento" ADD CONSTRAINT "FK_Lancamento_idClienteFavorecido_ManyToOne" FOREIGN KEY ("id_cliente_favorecido") REFERENCES "cliente_favorecido"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transacao" ADD CONSTRAINT "FK_Transacao_pagador_ManyToOne" FOREIGN KEY ("pagadorId") REFERENCES "pagador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transacao" ADD CONSTRAINT "FK_Transacao_status_ManyToOne" FOREIGN KEY ("statusId") REFERENCES "transacao_status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "header_arquivo" ADD CONSTRAINT "FK_HeaderArquivo_transacao_ManyToOne" FOREIGN KEY ("transacaoId") REFERENCES "transacao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" ADD CONSTRAINT "FK_ArquivoPublicacao_headerArquivo_ManyToOne" FOREIGN KEY ("headerArquivoId") REFERENCES "header_arquivo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forgot" ADD CONSTRAINT "FK_Forgot_user_ManyToOne" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invite" ADD CONSTRAINT "FK_Invite_user_ManyToOne" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invite" ADD CONSTRAINT "FK_Invite_inviteStatus_ManyToOne" FOREIGN KEY ("inviteStatusId") REFERENCES "invite_status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "setting" ADD CONSTRAINT "FK_Setting_settingType_ManyToOne" FOREIGN KEY ("settingTypeId") REFERENCES "setting_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "extrato_header_lote" ADD CONSTRAINT "FK_ExtratoHeaderLote_extratoHeaderArquivo_ManyToOne" FOREIGN KEY ("extratoHeaderArquivoId") REFERENCES "extrato_header_arquivo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "extrato_detalhe_e" ADD CONSTRAINT "FK_ExtratoDetalheE_extratoHeaderLote_ManyToOne" FOREIGN KEY ("extratoHeaderLoteId") REFERENCES "extrato_header_lote"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "header_lote" ADD CONSTRAINT "FK_HeaderLote_headerArquivo_ManyToOne" FOREIGN KEY ("headerArquivoId") REFERENCES "header_arquivo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "header_lote" ADD CONSTRAINT "FK_HeaderLote_pagador_ManyToOne" FOREIGN KEY ("pagadorId") REFERENCES "pagador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" ADD CONSTRAINT "FK_DetalheA_headerLote_ManyToOne" FOREIGN KEY ("headerLoteId") REFERENCES "header_lote"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" ADD CONSTRAINT "FK_DetalheA_clienteFavorecido_ManyToOne" FOREIGN KEY ("clienteFavorecidoId") REFERENCES "cliente_favorecido"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD CONSTRAINT "FK_ItemTransacao_transacao_ManyToOne" FOREIGN KEY ("transacaoId") REFERENCES "transacao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD CONSTRAINT "FK_ItemTransacao_clienteFavorecido_ManyToOne" FOREIGN KEY ("clienteFavorecidoId") REFERENCES "cliente_favorecido"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD CONSTRAINT "FK_ItemTransacao_detalheA_OneToOne" FOREIGN KEY ("detalheAId") REFERENCES "detalhe_a"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD CONSTRAINT "FK_ItemTransacao_status_ManyToOne" FOREIGN KEY ("statusId") REFERENCES "item_transacao_status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalhe_b" ADD CONSTRAINT "FK_DetalheB_detalheA_OneToOne" FOREIGN KEY ("detalheAId") REFERENCES "detalhe_a"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "detalhe_b" DROP CONSTRAINT "FK_DetalheB_detalheA_OneToOne"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP CONSTRAINT "FK_ItemTransacao_status_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP CONSTRAINT "FK_ItemTransacao_detalheA_OneToOne"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP CONSTRAINT "FK_ItemTransacao_clienteFavorecido_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP CONSTRAINT "FK_ItemTransacao_transacao_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" DROP CONSTRAINT "FK_DetalheA_clienteFavorecido_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" DROP CONSTRAINT "FK_DetalheA_headerLote_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "header_lote" DROP CONSTRAINT "FK_HeaderLote_pagador_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "header_lote" DROP CONSTRAINT "FK_HeaderLote_headerArquivo_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "extrato_detalhe_e" DROP CONSTRAINT "FK_ExtratoDetalheE_extratoHeaderLote_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "extrato_header_lote" DROP CONSTRAINT "FK_ExtratoHeaderLote_extratoHeaderArquivo_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "setting" DROP CONSTRAINT "FK_Setting_settingType_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "invite" DROP CONSTRAINT "FK_Invite_inviteStatus_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "invite" DROP CONSTRAINT "FK_Invite_user_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "forgot" DROP CONSTRAINT "FK_Forgot_user_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" DROP CONSTRAINT "FK_ArquivoPublicacao_headerArquivo_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "header_arquivo" DROP CONSTRAINT "FK_HeaderArquivo_transacao_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "transacao" DROP CONSTRAINT "FK_Transacao_status_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "transacao" DROP CONSTRAINT "FK_Transacao_pagador_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "lancamento" DROP CONSTRAINT "FK_Lancamento_idClienteFavorecido_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "lancamento" DROP CONSTRAINT "FK_Lancamento_user_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "cliente_favorecido" DROP CONSTRAINT "FK_ClienteFavorecido_user_OneToOne"`);
        await queryRunner.query(`ALTER TABLE "cliente_favorecido" DROP CONSTRAINT "FK_ClienteFavorecido_permissionarioRole_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_User_permissionarioRole_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_User_status_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_User_role_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_User_photo_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" DROP COLUMN "quantidadeMoeda"`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" ADD "quantidadeMoeda" integer`);
        await queryRunner.query(`ALTER TABLE "header_lote" DROP COLUMN "loteServico"`);
        await queryRunner.query(`ALTER TABLE "header_lote" ADD "loteServico" character varying`);
        await queryRunner.query(`ALTER TABLE "header_arquivo" DROP COLUMN "dataGeracao"`);
        await queryRunner.query(`ALTER TABLE "header_arquivo" ADD "dataGeracao" character varying`);
        await queryRunner.query(`ALTER TABLE "transacao" ALTER COLUMN "valorTotalTransacaoCaptura" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "transacao" ALTER COLUMN "valorTotalTransacaoLiquido" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "transacao" ALTER COLUMN "valorDescontoTaxa" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "transacao" DROP COLUMN "valorTotalTransacaoBruto"`);
        await queryRunner.query(`ALTER TABLE "transacao" ADD "valorTotalTransacaoBruto" integer`);
        await queryRunner.query(`ALTER TABLE "transacao" DROP COLUMN "quantidadeTotalTransacao"`);
        await queryRunner.query(`ALTER TABLE "transacao" ADD "quantidadeTotalTransacao" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "transacao" ALTER COLUMN "valorRateioDebito" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "transacao" ALTER COLUMN "valorRateioCredito" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "transacao" ALTER COLUMN "servico" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "detalhe_b" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP COLUMN "statusId"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP CONSTRAINT "UQ_611a02b09938bef0bc91cc85e86"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP COLUMN "detalheAId"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP COLUMN "versaoOrdemPagamento"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP COLUMN "dataOrdem"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP COLUMN "nomeOperadora"`);
        await queryRunner.query(`ALTER TABLE "header_lote" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" DROP COLUMN "idDetalheARetorno"`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" DROP COLUMN "dataVencimento"`);
        await queryRunner.query(`ALTER TABLE "transacao" DROP COLUMN "statusId"`);
        await queryRunner.query(`ALTER TABLE "transacao" DROP COLUMN "versaoOrdemPagamento"`);
        await queryRunner.query(`ALTER TABLE "transacao" DROP COLUMN "idConsorcio"`);
        await queryRunner.query(`ALTER TABLE "transacao" DROP COLUMN "idOperadora"`);
        await queryRunner.query(`ALTER TABLE "lancamento" DROP COLUMN "data_lancamento"`);
        await queryRunner.query(`ALTER TABLE "cliente_favorecido" DROP CONSTRAINT "UQ_0d5a5a996843f1f5e3f0e5ca380"`);
        await queryRunner.query(`ALTER TABLE "cliente_favorecido" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "cliente_favorecido" DROP COLUMN "permissionarioRoleId"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "permissionarioRoleId"`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" ADD "dtVencimento" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "item_transacao_status"`);
        await queryRunner.query(`DROP TABLE "extrato_detalhe_e"`);
        await queryRunner.query(`DROP TABLE "extrato_header_lote"`);
        await queryRunner.query(`DROP TABLE "extrato_header_arquivo"`);
        await queryRunner.query(`DROP TABLE "transacao_status"`);
        await queryRunner.query(`DROP TABLE "permissionario_role"`);
        await queryRunner.query(`ALTER TABLE "detalhe_b" ADD CONSTRAINT "FK_2c8fd111d9b6ad8e653cdbf725f" FOREIGN KEY ("detalheAId") REFERENCES "detalhe_a"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD CONSTRAINT "FK_04f9231ba148125f267dd160196" FOREIGN KEY ("transacaoId") REFERENCES "transacao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD CONSTRAINT "FK_67142ca27ead7b1bccbbc968c4b" FOREIGN KEY ("clienteFavorecidoId") REFERENCES "cliente_favorecido"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" ADD CONSTRAINT "FK_7228a16907c82f80e733dcb465b" FOREIGN KEY ("headerLoteId") REFERENCES "header_lote"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" ADD CONSTRAINT "FK_b5a7c03d9250881766627229e5d" FOREIGN KEY ("clienteFavorecidoId") REFERENCES "header_lote"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "header_lote" ADD CONSTRAINT "FK_cd9a79df522dbe1b057230614e9" FOREIGN KEY ("headerArquivoId") REFERENCES "header_arquivo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "header_lote" ADD CONSTRAINT "FK_75f6c2ed71c10935915157b45f9" FOREIGN KEY ("pagadorId") REFERENCES "pagador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "setting" ADD CONSTRAINT "FK_a5bc5fbecc0b218be61ef25b725" FOREIGN KEY ("settingTypeId") REFERENCES "setting_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invite" ADD CONSTRAINT "FK_91bfeec7a9574f458e5b592472d" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invite" ADD CONSTRAINT "FK_118ec7f671543d9b992512e7cb9" FOREIGN KEY ("inviteStatusId") REFERENCES "invite_status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forgot" ADD CONSTRAINT "FK_31f3c80de0525250f31e23a9b83" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" ADD CONSTRAINT "FK_9034ea1202b6574b75a2304d419" FOREIGN KEY ("headerArquivoId") REFERENCES "header_arquivo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "header_arquivo" ADD CONSTRAINT "FK_2ecc2606a7de054a63c0e22f206" FOREIGN KEY ("transacaoId") REFERENCES "transacao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transacao" ADD CONSTRAINT "FK_097c8d865615a7ec0516929b65f" FOREIGN KEY ("pagadorId") REFERENCES "pagador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lancamento" ADD CONSTRAINT "FK_80f6744ced95ab9e8dd0b212fee" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lancamento" ADD CONSTRAINT "FK_ea066846cf244204c813b72ff50" FOREIGN KEY ("id_cliente_favorecido") REFERENCES "cliente_favorecido"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_75e2be4ce11d447ef43be0e374f" FOREIGN KEY ("photoId") REFERENCES "file"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c28e52f758e7bbc53828db92194" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_dc18daa696860586ba4667a9d31" FOREIGN KEY ("statusId") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
