import { MigrationInterface, QueryRunner } from "typeorm";

export class Createtables1715189568931 implements MigrationInterface {
    name = 'Createtables1715189568931'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "cliente_favorecido" ("id" SERIAL NOT NULL, "nome" character varying(150) NOT NULL, "cpfCnpj" character varying(14), "codigoBanco" character varying(10), "agencia" character varying(5), "dvAgencia" character varying(2), "contaCorrente" character varying(12), "dvContaCorrente" character varying(2), "logradouro" character varying(200), "numero" character varying(15), "complemento" character varying(100), "bairro" character varying(150), "cidade" character varying(150), "cep" character varying(5), "complementoCep" character varying(3), "uf" character varying(2), "tipo" character varying, CONSTRAINT "UQ_e41ab42b4e6c8bdba22dae84e7f" UNIQUE ("cpfCnpj"), CONSTRAINT "PK_ClienteFavorecido_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pagador" ("id" SERIAL NOT NULL, "nomeEmpresa" character varying(150) NOT NULL, "agencia" character varying(5), "dvAgencia" character varying(2), "conta" character varying(12), "dvConta" character varying(2), "logradouro" character varying(200), "numero" character varying(15), "complemento" character varying(100), "bairro" character varying(150), "cidade" character varying(150), "cep" character varying(5), "complementoCep" character varying(3), "uf" character varying(2), "cpfCnpj" character varying(14), CONSTRAINT "PK_Pagador_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transacao_ocorrencia" ("id" SERIAL NOT NULL, "code" character varying(2) NOT NULL, "message" character varying(100) NOT NULL, "transacaoId" integer, CONSTRAINT "UQ_d0e6bda82c6af3340f372e70786" UNIQUE ("code"), CONSTRAINT "PK_Ocorrencia_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transacao_status" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_TransacaoStatus_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transacao" ("id" SERIAL NOT NULL, "dataOrdem" TIMESTAMP, "dataPagamento" TIMESTAMP, "idOrdemPagamento" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "pagadorId" integer, "statusId" integer NOT NULL, CONSTRAINT "UQ_f810a19a720003d3e7544cd3d6a" UNIQUE ("idOrdemPagamento"), CONSTRAINT "PK_Transacao_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "file" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "path" character varying NOT NULL, CONSTRAINT "PK_File_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_Role_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "status" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_Status_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "email" character varying, "password" character varying, "provider" character varying NOT NULL DEFAULT 'email', "socialId" character varying, "firstName" character varying, "lastName" character varying, "fullName" character varying, "hash" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "permitCode" character varying, "cpfCnpj" character varying, "bankCode" integer, "bankAgency" character varying(4), "bankAccount" character varying(20), "bankAccountDigit" character varying(2), "phone" character varying, "isSgtuBlocked" boolean, "passValidatorId" character varying, "photoId" uuid, "roleId" integer, "statusId" integer, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_User_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_User_socialId" ON "user" ("socialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_User_firstName" ON "user" ("firstName") `);
        await queryRunner.query(`CREATE INDEX "IDX_User_lastName" ON "user" ("lastName") `);
        await queryRunner.query(`CREATE INDEX "IDX_User_fullName" ON "user" ("fullName") `);
        await queryRunner.query(`CREATE INDEX "IDX_User_hash" ON "user" ("hash") `);
        await queryRunner.query(`CREATE TABLE "lancamento" ("id" SERIAL NOT NULL, "descricao" character varying NOT NULL, "valor" numeric NOT NULL, "data_ordem" TIMESTAMP NOT NULL DEFAULT now(), "data_pgto" TIMESTAMP NOT NULL DEFAULT now(), "data_lancamento" TIMESTAMP NOT NULL DEFAULT now(), "auth_usersIds" character varying, "userId" integer NOT NULL, "algoritmo" character varying NOT NULL, "glosa" character varying NOT NULL, "recurso" character varying NOT NULL, "anexo" character varying NOT NULL, "valor_a_pagar" numeric NOT NULL, "numero_processo" character varying NOT NULL, "transacaoId" integer, "id_cliente_favorecido" integer, CONSTRAINT "PK_Lancamento_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bank" ("id" SERIAL NOT NULL, "ispb" integer NOT NULL, "name" character varying NOT NULL, "code" integer NOT NULL, "fullName" character varying NOT NULL, "isAllowed" boolean NOT NULL, CONSTRAINT "UQ_644e44c1a3cb9d4b431fb080160" UNIQUE ("ispb"), CONSTRAINT "UQ_efdd3f589f04cd21d79136de1aa" UNIQUE ("code"), CONSTRAINT "PK_Bank_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "header_arquivo_status" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_HeaderArquivoStatus_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "header_arquivo" ("id" SERIAL NOT NULL, "tipoArquivo" integer NOT NULL, "codigoBanco" character varying(10), "tipoInscricao" character varying(2), "numeroInscricao" character varying(14), "codigoConvenio" character varying(6), "parametroTransmissao" character varying(2), "agencia" character varying(5), "dvAgencia" character varying(1), "numeroConta" character varying(12), "dvConta" character varying(1), "nomeEmpresa" character varying(100), "dataGeracao" TIMESTAMP, "horaGeracao" TIME, "nsa" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "transacaoId" integer, "statusId" integer, CONSTRAINT "PK_HeaderArquivo_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "arquivo_publicacao" ("id" SERIAL NOT NULL, "idHeaderLote" character varying, "dataGeracaoRemessa" TIMESTAMP, "horaGeracaoRemessa" TIMESTAMP, "isPago" boolean NOT NULL, "dataGeracaoRetorno" TIMESTAMP, "horaGeracaoRetorno" TIMESTAMP, "loteServico" integer, "nomePagador" character varying NOT NULL, "agenciaPagador" character varying NOT NULL, "dvAgenciaPagador" character varying NOT NULL, "contaPagador" character varying NOT NULL, "dvContaPagador" character varying NOT NULL, "nomeCliente" character varying NOT NULL, "cpfCnpjCliente" character varying NOT NULL, "codigoBancoCliente" character varying NOT NULL, "agenciaCliente" character varying NOT NULL, "dvAgenciaCliente" character varying NOT NULL, "contaCorrenteCliente" character varying NOT NULL, "dvContaCorrenteCliente" character varying NOT NULL, "dataVencimento" character varying, "valorLancamento" character varying, "dataEfetivacao" character varying, "valorRealEfetivado" character varying, "idDetalheARetorno" integer, "idOrdemPagamento" character varying NOT NULL, "idConsorcio" character varying NOT NULL, "idOperadora" character varying NOT NULL, "dataOrdem" TIMESTAMP NOT NULL, "nomeConsorcio" character varying NOT NULL, "nomeOperadora" character varying NOT NULL, "valorTotalTransacaoLiquido" numeric(13,2) NOT NULL, "headerArquivoId" integer, "transacaoId" integer, CONSTRAINT "PK_ArquivoPublicacao_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mail_count" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "recipientCount" integer NOT NULL, "maxRecipients" integer NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_426e0538ee56b8771e2cc5fee07" UNIQUE ("email"), CONSTRAINT "PK_MailCount_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "forgot" ("id" SERIAL NOT NULL, "hash" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" integer, CONSTRAINT "PK_Forgot_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_Forgot_hash" ON "forgot" ("hash") `);
        await queryRunner.query(`CREATE TABLE "info" ("id" integer NOT NULL, "name" character varying NOT NULL, "value" character varying NOT NULL, "version" character varying, CONSTRAINT "UQ_916df6cf672c24f99ceab946a88" UNIQUE ("name"), CONSTRAINT "PK_Info_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invite_status" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_bfcd7854096256be37cd3b47b16" UNIQUE ("name"), CONSTRAINT "PK_InviteStatus_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting_type" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_a4b944907a7b757fc5a4f91ba5e" UNIQUE ("name"), CONSTRAINT "PK_SettingType_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting" ("id" integer NOT NULL, "name" character varying NOT NULL, "value" character varying NOT NULL, "version" character varying, "editable" boolean NOT NULL, "settingTypeId" integer, CONSTRAINT "UQ_Setting_name_version" UNIQUE ("name", "version"), CONSTRAINT "PK_Setting_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invite" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "hash" character varying NOT NULL, "smtpErrorCode" integer, "httpErrorCode" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP, "failedAt" TIMESTAMP, "sentAt" TIMESTAMP, "deletedAt" TIMESTAMP, "userId" integer, "inviteStatusId" integer, CONSTRAINT "UQ_dbcbf85f7e3e27d864631d1cf14" UNIQUE ("hash"), CONSTRAINT "PK_Invite_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "extrato_header_arquivo" ("id" SERIAL NOT NULL, "tipoArquivo" integer, "codigoBanco" character varying(10), "tipoInscricao" character varying(2), "numeroInscricao" character varying(14), "codigoConvenio" character varying(6), "parametroTransmissao" character varying(2), "agencia" character varying(5), "dvAgencia" character varying(1), "numeroConta" character varying(12), "dvConta" character varying(1), "nomeEmpresa" character varying(100), "dataGeracao" TIMESTAMP, "horaGeracao" TIME, "nsa" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ExtratoHeaderArquivo_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "extrato_header_lote" ("id" SERIAL NOT NULL, "loteServico" integer, "tipoInscricao" character varying, "numeroInscricao" character varying, "codigoConvenioBanco" character varying, "dataSaldoInicial" TIMESTAMP NOT NULL, "valorSaldoInicial" numeric(16,2) NOT NULL, "situacaoSaldoInicial" character varying(1) NOT NULL, "posicaoSaldoInicial" character varying(1) NOT NULL, "tipoMoeda" character varying(3) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "extratoHeaderArquivoId" integer, CONSTRAINT "PK_ExtratoHeaderLote_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "extrato_detalhe_e" ("id" SERIAL NOT NULL, "loteServico" integer NOT NULL, "nsr" integer NOT NULL, "tipoInscricao" character varying NOT NULL, "numeroInscricao" character varying NOT NULL, "codigoConvenioBanco" character varying NOT NULL, "agencia" character varying NOT NULL, "dvAgencia" character varying NOT NULL, "conta" character varying NOT NULL, "dvConta" character varying NOT NULL, "dvAgenciaConta" character varying NOT NULL, "nomeEmpresa" character varying NOT NULL, "dataLancamento" TIMESTAMP NOT NULL, "valorLancamento" numeric(16,2), "tipoLancamento" character varying NOT NULL, "categoriaLancamento" character varying NOT NULL, "codigoHistoricoBanco" character varying NOT NULL, "descricaoHistoricoBanco" character varying NOT NULL, "numeroDocumento" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "extratoHeaderLoteId" integer, CONSTRAINT "PK_ExtratoDetalheE_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "header_lote" ("id" SERIAL NOT NULL, "loteServico" integer, "tipoInscricao" character varying, "numeroInscricao" character varying, "codigoConvenioBanco" character varying, "tipoCompromisso" character varying, "parametroTransmissao" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "headerArquivoId" integer, "pagadorId" integer, CONSTRAINT "PK_HeaderLote_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "detalhe_a" ("id" SERIAL NOT NULL, "loteServico" integer, "finalidadeDOC" character varying, "numeroDocumentoEmpresa" integer NOT NULL, "dataVencimento" TIMESTAMP, "tipoMoeda" character varying, "quantidadeMoeda" numeric(10,5), "valorLancamento" numeric(13,2), "numeroDocumentoBanco" character varying, "quantidadeParcelas" integer, "indicadorBloqueio" character varying, "indicadorFormaParcelamento" character varying, "periodoVencimento" TIMESTAMP, "numeroParcela" integer, "dataEfetivacao" TIMESTAMP, "valorRealEfetivado" numeric(13,2), "nsr" integer NOT NULL, "ocorrencias" character varying(10), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "headerLoteId" integer, "clienteFavorecidoId" integer, CONSTRAINT "PK_DetalheA_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "detalhe_b" ("id" SERIAL NOT NULL, "nsr" integer NOT NULL, "dataVencimento" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "detalheAId" integer, CONSTRAINT "REL_2c8fd111d9b6ad8e653cdbf725" UNIQUE ("detalheAId"), CONSTRAINT "PK_DetalheB_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "item_transacao_status" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_ItemTransacaoStatusId_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "item_transacao" ("id" SERIAL NOT NULL, "dataProcessamento" TIMESTAMP NOT NULL DEFAULT now(), "dataCaptura" TIMESTAMP NOT NULL DEFAULT now(), "nomeConsorcio" character varying(200), "nomeOperadora" character varying(200), "favorecidoCpfCnpj" character varying NOT NULL, "valor" numeric(10,5), "idOrdemPagamento" character varying, "idOperadora" character varying, "idConsorcio" character varying, "dataLancamento" TIMESTAMP, "dataOrdem" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "transacaoId" integer, "clienteFavorecidoId" integer, "detalheAId" integer, "statusId" integer NOT NULL, CONSTRAINT "REL_611a02b09938bef0bc91cc85e8" UNIQUE ("detalheAId"), CONSTRAINT "PK_ItemTransacao_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "transacao_ocorrencia" ADD CONSTRAINT "FK_TransacaoOcorrencia_transacao_ManyToOne" FOREIGN KEY ("transacaoId") REFERENCES "transacao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transacao" ADD CONSTRAINT "FK_Transacao_pagador_ManyToOne" FOREIGN KEY ("pagadorId") REFERENCES "pagador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transacao" ADD CONSTRAINT "FK_Transacao_status_ManyToOne" FOREIGN KEY ("statusId") REFERENCES "transacao_status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_User_photo_ManyToOne" FOREIGN KEY ("photoId") REFERENCES "file"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_User_role_ManyToOne" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_User_status_ManyToOne" FOREIGN KEY ("statusId") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lancamento" ADD CONSTRAINT "FK_Lancamento_transacao_ManyToOne" FOREIGN KEY ("transacaoId") REFERENCES "transacao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lancamento" ADD CONSTRAINT "FK_Lancamento_user_ManyToOne" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lancamento" ADD CONSTRAINT "FK_Lancamento_idClienteFavorecido_ManyToOne" FOREIGN KEY ("id_cliente_favorecido") REFERENCES "cliente_favorecido"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "header_arquivo" ADD CONSTRAINT "FK_HeaderArquivo_transacao_ManyToOne" FOREIGN KEY ("transacaoId") REFERENCES "transacao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "header_arquivo" ADD CONSTRAINT "FK_HeaderArquivo_status_ManyToOne" FOREIGN KEY ("statusId") REFERENCES "header_arquivo_status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" ADD CONSTRAINT "FK_ArquivoPublicacao_headerArquivo_ManyToOne" FOREIGN KEY ("headerArquivoId") REFERENCES "header_arquivo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" ADD CONSTRAINT "FK_ArquivoPublicacao_transacao_ManyToOne" FOREIGN KEY ("transacaoId") REFERENCES "transacao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forgot" ADD CONSTRAINT "FK_Forgot_user_ManyToOne" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "setting" ADD CONSTRAINT "FK_Setting_settingType_ManyToOne" FOREIGN KEY ("settingTypeId") REFERENCES "setting_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invite" ADD CONSTRAINT "FK_Invite_user_ManyToOne" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invite" ADD CONSTRAINT "FK_Invite_inviteStatus_ManyToOne" FOREIGN KEY ("inviteStatusId") REFERENCES "invite_status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "extrato_header_lote" ADD CONSTRAINT "FK_ExtratoHeaderLote_extratoHeaderArquivo_ManyToOne" FOREIGN KEY ("extratoHeaderArquivoId") REFERENCES "extrato_header_arquivo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "extrato_detalhe_e" ADD CONSTRAINT "FK_ExtratoDetalheE_extratoHeaderLote_ManyToOne" FOREIGN KEY ("extratoHeaderLoteId") REFERENCES "extrato_header_lote"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "header_lote" ADD CONSTRAINT "FK_HeaderLote_headerArquivo_ManyToOne" FOREIGN KEY ("headerArquivoId") REFERENCES "header_arquivo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "header_lote" ADD CONSTRAINT "FK_HeaderLote_pagador_ManyToOne" FOREIGN KEY ("pagadorId") REFERENCES "pagador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" ADD CONSTRAINT "FK_DetalheA_headerLote_ManyToOne" FOREIGN KEY ("headerLoteId") REFERENCES "header_lote"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" ADD CONSTRAINT "FK_DetalheA_clienteFavorecido_ManyToOne" FOREIGN KEY ("clienteFavorecidoId") REFERENCES "cliente_favorecido"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalhe_b" ADD CONSTRAINT "FK_DetalheB_detalheA_OneToOne" FOREIGN KEY ("detalheAId") REFERENCES "detalhe_a"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD CONSTRAINT "FK_ItemTransacao_transacao_ManyToOne" FOREIGN KEY ("transacaoId") REFERENCES "transacao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD CONSTRAINT "FK_ItemTransacao_clienteFavorecido_ManyToOne" FOREIGN KEY ("clienteFavorecidoId") REFERENCES "cliente_favorecido"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD CONSTRAINT "FK_ItemTransacao_detalheA_OneToOne" FOREIGN KEY ("detalheAId") REFERENCES "detalhe_a"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_transacao" ADD CONSTRAINT "FK_ItemTransacao_status_ManyToOne" FOREIGN KEY ("statusId") REFERENCES "item_transacao_status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP CONSTRAINT "FK_ItemTransacao_status_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP CONSTRAINT "FK_ItemTransacao_detalheA_OneToOne"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP CONSTRAINT "FK_ItemTransacao_clienteFavorecido_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "item_transacao" DROP CONSTRAINT "FK_ItemTransacao_transacao_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "detalhe_b" DROP CONSTRAINT "FK_DetalheB_detalheA_OneToOne"`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" DROP CONSTRAINT "FK_DetalheA_clienteFavorecido_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "detalhe_a" DROP CONSTRAINT "FK_DetalheA_headerLote_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "header_lote" DROP CONSTRAINT "FK_HeaderLote_pagador_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "header_lote" DROP CONSTRAINT "FK_HeaderLote_headerArquivo_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "extrato_detalhe_e" DROP CONSTRAINT "FK_ExtratoDetalheE_extratoHeaderLote_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "extrato_header_lote" DROP CONSTRAINT "FK_ExtratoHeaderLote_extratoHeaderArquivo_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "invite" DROP CONSTRAINT "FK_Invite_inviteStatus_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "invite" DROP CONSTRAINT "FK_Invite_user_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "setting" DROP CONSTRAINT "FK_Setting_settingType_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "forgot" DROP CONSTRAINT "FK_Forgot_user_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" DROP CONSTRAINT "FK_ArquivoPublicacao_transacao_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "arquivo_publicacao" DROP CONSTRAINT "FK_ArquivoPublicacao_headerArquivo_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "header_arquivo" DROP CONSTRAINT "FK_HeaderArquivo_status_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "header_arquivo" DROP CONSTRAINT "FK_HeaderArquivo_transacao_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "lancamento" DROP CONSTRAINT "FK_Lancamento_idClienteFavorecido_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "lancamento" DROP CONSTRAINT "FK_Lancamento_user_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "lancamento" DROP CONSTRAINT "FK_Lancamento_transacao_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_User_status_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_User_role_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_User_photo_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "transacao" DROP CONSTRAINT "FK_Transacao_status_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "transacao" DROP CONSTRAINT "FK_Transacao_pagador_ManyToOne"`);
        await queryRunner.query(`ALTER TABLE "transacao_ocorrencia" DROP CONSTRAINT "FK_TransacaoOcorrencia_transacao_ManyToOne"`);
        await queryRunner.query(`DROP TABLE "item_transacao"`);
        await queryRunner.query(`DROP TABLE "item_transacao_status"`);
        await queryRunner.query(`DROP TABLE "detalhe_b"`);
        await queryRunner.query(`DROP TABLE "detalhe_a"`);
        await queryRunner.query(`DROP TABLE "header_lote"`);
        await queryRunner.query(`DROP TABLE "extrato_detalhe_e"`);
        await queryRunner.query(`DROP TABLE "extrato_header_lote"`);
        await queryRunner.query(`DROP TABLE "extrato_header_arquivo"`);
        await queryRunner.query(`DROP TABLE "invite"`);
        await queryRunner.query(`DROP TABLE "setting"`);
        await queryRunner.query(`DROP TABLE "setting_type"`);
        await queryRunner.query(`DROP TABLE "invite_status"`);
        await queryRunner.query(`DROP TABLE "info"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_Forgot_hash"`);
        await queryRunner.query(`DROP TABLE "forgot"`);
        await queryRunner.query(`DROP TABLE "mail_count"`);
        await queryRunner.query(`DROP TABLE "arquivo_publicacao"`);
        await queryRunner.query(`DROP TABLE "header_arquivo"`);
        await queryRunner.query(`DROP TABLE "header_arquivo_status"`);
        await queryRunner.query(`DROP TABLE "bank"`);
        await queryRunner.query(`DROP TABLE "lancamento"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_User_hash"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_User_fullName"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_User_lastName"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_User_firstName"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_User_socialId"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "status"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "file"`);
        await queryRunner.query(`DROP TABLE "transacao"`);
        await queryRunner.query(`DROP TABLE "transacao_status"`);
        await queryRunner.query(`DROP TABLE "transacao_ocorrencia"`);
        await queryRunner.query(`DROP TABLE "pagador"`);
        await queryRunner.query(`DROP TABLE "cliente_favorecido"`);
    }

}
