export enum FormaLancamentoCaixa {
  CreditoContaCorrente = '01',
  ChequePagamento = '02',
  DOC = '03',
  CreditoContaPoupanca = '05',
  OPDisposicao = '10',
  PagamentoContasTributos = '11',
  PagamentoDARFSemBarras = '16',
  PagamentoGPSSemBarras = '17',
  LiquidacaoTitulosProprioBanco = '30',
  PagamentoTitulosOutrosBancos = '31',
  TED = '41',
  DebitoContaCorrenteRecebimento = '50',
  PagamentoGuiaDepositoJudicial = '71',
  PagamentoConcessionarias = '99',
}
