export enum Cnab104FormaLancamentoExtrato {
  CreditoContaCorrenteSalario = '01',
  ChequePagamentoAdministrativo = '02',
  DOC_TED = '03',
  CartaoSalario = '04',
  CreditoContaPoupanca = '05',
  OPDisposicao = '10',
  PagamentoContasTributosCodigoBarras = '11',
  TributoDARFNormal = '16',
  TributoGPS = '17',
  TributoDARFSimples = '18',
  TributoIPTU = '19',
  PagamentoComAutenticacao = '20',
  TributoDARJ = '21',
  TributoGARESPICMS = '22',
  TributoGARESPDR = '23',
  TributoGARESPITCMD = '24',
  TributoIPVA = '25',
  TributoLicenciamento = '26',
  TributoDPVAT = '27',
  LiquidacaoTitulosProprioBanco = '30',
  PagamentoTitulosOutrosBancos = '31',
  ExtratoContaCorrente = '40',
  TEDOutraTitularidade = '41',
  TEDMesmaTitularidade = '43',
  TEDTransferenciaContaInvestimento = '44',
  PIXTransferencia = '45',
  PIX_QRCode = '47',
  DebitoContaCorrente = '50',
  ExtratoGestaoCaixa = '70',
  DepositoJudicialContaCorrente = '71',
  DepositoJudicialPoupanca = '72',
  ExtratoContaInvestimento = '73',
  PagamentoTributosMunicipaisISSProprioBanco = '80',
  PagamentoTributosMunicipaisISSOutrosBancos = '81',

}
