export const UserFieldsSQL = `
  "user"."id" as "user_id",
  "user"."email" as "user_email",
  "user"."password" as "user_password",
  "user"."provider" as "user_provider",
  "user"."socialId" as "user_socialId",
  "user"."firstName" as "user_firstName",
  "user"."lastName" as "user_lastName",
  "user"."fullName" as "user_fullName",
  "user"."hash" as "user_hash",
  "user"."createdAt" as "user_createdAt",
  "user"."updatedAt" as "user_updatedAt",
  "user"."deletedAt" as "user_deletedAt",
  "user"."permitCode" as "user_permitCode",
  "user"."cpfCnpj" as "user_cpfCnpj",
  "user"."bankCode" as "user_bankCode",
  "user"."bankAgency" as "user_bankAgency",
  "user"."bankAccount" as "user_bankAccount",
  "user"."bankAccountDigit" as "user_bankAccountDigit",
  "user"."phone" as "user_phone",
  "user"."isSgtuBlocked" as "user_isSgtuBlocked",
  "user"."passValidatorId" as "user_passValidatorId",
  "user"."photoId" as "user_photoId",
  "user"."roleId" as "user_roleId",
  "user"."statusId" as "user_statusId"
`.replace(/\r\n|\n/g, '');
