const remessaCnab = [
  // Luciane: 4,13
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "8",
    consorcio: "STPL",
    idOperadora: "463453401",
    operadora: "******* ******* **** ********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "82773335791",
    nome: "LUCIANE PEREIRA LIMA LOUREIRO",
  },
  // Aguinaldo 4,13
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "8",
    consorcio: "STPL",
    idOperadora: "463422751",
    operadora: "********* ***** *******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "36980439715",
    nome: "AGUINALDO PAIVA RIBEIRO",
  },
  // Marcia duarte seixas
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463453085",
    operadora: "****** ****** ******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "02817598717",
    nome: "MARCIA DUARTE SEIXAS",
  },
  // Jocimar
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463423222",
    operadora: "******* ***** ******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "02486069720",
    nome: "JOCIMAR GOMES DUARTE",
  },
  // Ines
  {
    dataOrdem: "2024-06-20",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463413106",
    operadora: "**** *********",
    idOrdemPagamento: "338",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "7bcba650c069552886d5571ba3a056a9d3bf8789",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "79464637749",
    nome: "INES FERNANDES",
  },
  // Carlos
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463516487",
    operadora: "****** *** ****** ******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "11686961782",
    nome: "CARLOS DOS SANTOS SOARES",
  },
  // Mario Felix
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463453182",
    operadora: "***** ***** ******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "99427036753",
    nome: "MARIO FELIX SEIXAS",
  },
  // Jose martins
  {
    dataOrdem: "2024-06-18",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463553996",
    operadora: "**** ******* *******",
    idOrdemPagamento: "336",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "54810183734",
    nome: "JOSE MARTINS CORREIA",
  },
  // Dimas
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463553589",
    operadora: "***** ********* ** ****** ******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "02950233767",
    nome: "DIMAS CASCIMIRO DE ARAUJO JUNIOR",
  },
  // Renato Maxiqueira
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463452921",
    operadora: "****** **********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "01228098743",
    nome: "RENATO MAXIQUEIRA",
  },
  // Luiz carlos
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463423091",
    operadora: "**** ****** ******* ** ****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "66172969749",
    nome: "LUIZ CARLOS FURTADO DE MELO",
  },
  // Andre luis
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463554555",
    operadora: "***** **** *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "07713033785",
    nome: "ANDRE LUIS LOPES",
  },
  // Yuri
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463575620",
    operadora: "**** ********* **********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "16494896766",
    nome: "YURI DELLATORE MACIQUEIRA",
  },
  // Mario Luis
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463556092",
    operadora: "***** **** ***** *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "92432395700",
    nome: "MARIO LUIS ROMAO NUNES",
  },
  // Jose alirio
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463572898",
    operadora: "**** ****** ******* *******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "67293352700",
    nome: "JOSE ALIRIO PEREIRA DELFINO",
  },
  // Ricardo Henrique
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463513752",
    operadora: "******* ******** ** ***** *********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "30828026807",
    nome: "RICARDO HENRIQUE DA SILVA FERNANDES",
  },
  // Rosemar furtado
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463573350",
    operadora: "******* ******* ********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "90885783700",
    nome: "ROSEMAR FURTADO GONZALEZ",
  },
  // Feoravante
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463565416",
    operadora: "********** ********* *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 2,
    valorDebito: 8.6,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 8.6,
    valorDescontoTaxa: 0.344,
    valorTotalTransacaoLiquido: 8.256,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "07077394700",
    nome: "FEORAVANTE RODRIGUES SILVA",
  },
  // rozemeri
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463423170",
    operadora: "******** ****** ** *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 2,
    valorDebito: 8.6,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 8.6,
    valorDescontoTaxa: 0.344,
    valorTotalTransacaoLiquido: 8.256,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "01867921740",
    nome: "ROZEMERI VIEIRA DA SILVA",
  },
  // Silvia
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463415449",
    operadora: "****** **** **********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 4,
    valorDebito: 17.2,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 17.2,
    valorDescontoTaxa: 0.688,
    valorTotalTransacaoLiquido: 16.512,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "07490817757",
    nome: "SILVIA REIS MACIQUEIRA",
  },
  // maria da guia: 12,38 (4,13 x3)
  {
    dataOrdem: "2024-06-08",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463416372",
    operadora: "***** ** **** ****** ** *****",
    idOrdemPagamento: "326",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "03818429405",
    nome: "MARIA DA GUIA BARROS DA COSTA",
  },
  {
    dataOrdem: "2024-06-12",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463416372",
    operadora: "***** ** **** ****** ** *****",
    idOrdemPagamento: "330",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "03818429405",
    nome: "MARIA DA GUIA BARROS DA COSTA",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463416372",
    operadora: "***** ** **** ****** ** *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "03818429405",
    nome: "MARIA DA GUIA BARROS DA COSTA",
  },
  // Joao sales 4,13
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463413258",
    operadora: "**** ***** ** ***********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "29709920782",
    nome: "JOAO SALES DE ALBUQUERQUE",
  },
  // Jose dias ximenes
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463494930",
    operadora: "**** **** *******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "46285911649",
    nome: "JOSE DIAS XIMENES",
  },
  // Eliane
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463423161",
    operadora: "****** ****** ** *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "07575981705",
    nome: "ELIANE VIEIRA DA SILVA",
  },
  // Roseval
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463554591",
    operadora: "******* ******* ** *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 2,
    valorDebito: 8.6,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 8.6,
    valorDescontoTaxa: 0.344,
    valorTotalTransacaoLiquido: 8.256,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "86660098704",
    nome: "ROSEVAL PEREIRA DE SOUZA",
  },
];

const remessa14 = [
  {
    dataOrdem: "2024-06-08",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463416372",
    operadora: "***** ** **** ****** ** *****",
    idOrdemPagamento: "326",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "03818429405",
    nome: "MARIA DA GUIA BARROS DA COSTA",
  },
  {
    dataOrdem: "2024-06-12",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463416372",
    operadora: "***** ** **** ****** ** *****",
    idOrdemPagamento: "330",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "03818429405",
    nome: "MARIA DA GUIA BARROS DA COSTA",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "8",
    consorcio: "STPL",
    idOperadora: "463453401",
    operadora: "******* ******* **** ********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "82773335791",
    nome: "LUCIANE PEREIRA LIMA LOUREIRO",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "8",
    consorcio: "STPL",
    idOperadora: "463422751",
    operadora: "********* ***** *******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "36980439715",
    nome: "AGUINALDO PAIVA RIBEIRO",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463453085",
    operadora: "****** ****** ******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "02817598717",
    nome: "MARCIA DUARTE SEIXAS",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463423222",
    operadora: "******* ***** ******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "02486069720",
    nome: "JOCIMAR GOMES DUARTE",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463413106",
    operadora: "**** *********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "79464637749",
    nome: "INES FERNANDES",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463516487",
    operadora: "****** *** ****** ******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "11686961782",
    nome: "CARLOS DOS SANTOS SOARES",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463413258",
    operadora: "**** ***** ** ***********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "29709920782",
    nome: "JOAO SALES DE ALBUQUERQUE",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463453182",
    operadora: "***** ***** ******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "99427036753",
    nome: "MARIO FELIX SEIXAS",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463494930",
    operadora: "**** **** *******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "46285911649",
    nome: "JOSE DIAS XIMENES",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463553996",
    operadora: "**** ******* *******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "54810183734",
    nome: "JOSE MARTINS CORREIA",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463553589",
    operadora: "***** ********* ** ****** ******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "02950233767",
    nome: "DIMAS CASCIMIRO DE ARAUJO JUNIOR",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463452921",
    operadora: "****** **********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "01228098743",
    nome: "RENATO MAXIQUEIRA",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463423091",
    operadora: "**** ****** ******* ** ****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "66172969749",
    nome: "LUIZ CARLOS FURTADO DE MELO",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463554555",
    operadora: "***** **** *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "07713033785",
    nome: "ANDRE LUIS LOPES",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463575620",
    operadora: "**** ********* **********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "16494896766",
    nome: "YURI DELLATORE MACIQUEIRA",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463556092",
    operadora: "***** **** ***** *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "92432395700",
    nome: "MARIO LUIS ROMAO NUNES",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463572898",
    operadora: "**** ****** ******* *******",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "67293352700",
    nome: "JOSE ALIRIO PEREIRA DELFINO",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463423161",
    operadora: "****** ****** ** *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "07575981705",
    nome: "ELIANE VIEIRA DA SILVA",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463513752",
    operadora: "******* ******** ** ***** *********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "30828026807",
    nome: "RICARDO HENRIQUE DA SILVA FERNANDES",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463416372",
    operadora: "***** ** **** ****** ** *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "03818429405",
    nome: "MARIA DA GUIA BARROS DA COSTA",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463573350",
    operadora: "******* ******* ********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "90885783700",
    nome: "ROSEMAR FURTADO GONZALEZ",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463565416",
    operadora: "********** ********* *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 2,
    valorDebito: 8.6,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 8.6,
    valorDescontoTaxa: 0.344,
    valorTotalTransacaoLiquido: 8.256,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "07077394700",
    nome: "FEORAVANTE RODRIGUES SILVA",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463423170",
    operadora: "******** ****** ** *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 2,
    valorDebito: 8.6,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 8.6,
    valorDescontoTaxa: 0.344,
    valorTotalTransacaoLiquido: 8.256,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "01867921740",
    nome: "ROZEMERI VIEIRA DA SILVA",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463554591",
    operadora: "******* ******* ** *****",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 2,
    valorDebito: 8.6,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 8.6,
    valorDescontoTaxa: 0.344,
    valorTotalTransacaoLiquido: 8.256,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "86660098704",
    nome: "ROSEVAL PEREIRA DE SOUZA",
  },
  {
    dataOrdem: "2024-06-13",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463415449",
    operadora: "****** **** **********",
    idOrdemPagamento: "331",
    quantidadeTransacaoDebito: 4,
    valorDebito: 17.2,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 17.2,
    valorDescontoTaxa: 0.688,
    valorTotalTransacaoLiquido: 16.512,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "07490817757",
    nome: "SILVIA REIS MACIQUEIRA",
  },
];

const remessa21 = [
  {
    dataOrdem: "2024-06-15",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463423170",
    operadora: "******** ****** ** *****",
    idOrdemPagamento: "333",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "01867921740",
    nome: "ROZEMERI VIEIRA DA SILVA",
  },
  {
    dataOrdem: "2024-06-16",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463416372",
    operadora: "***** ** **** ****** ** *****",
    idOrdemPagamento: "334",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "03818429405",
    nome: "MARIA DA GUIA BARROS DA COSTA",
  },
  {
    dataOrdem: "2024-06-17",
    idConsorcio: "8",
    consorcio: "STPL",
    idOperadora: "463453401",
    operadora: "******* ******* **** ********",
    idOrdemPagamento: "335",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "82773335791",
    nome: "LUCIANE PEREIRA LIMA LOUREIRO",
  },
  {
    dataOrdem: "2024-06-17",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463413258",
    operadora: "**** ***** ** ***********",
    idOrdemPagamento: "335",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "29709920782",
    nome: "JOAO SALES DE ALBUQUERQUE",
  },
  {
    dataOrdem: "2024-06-18",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463553996",
    operadora: "**** ******* *******",
    idOrdemPagamento: "336",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "54810183734",
    nome: "JOSE MARTINS CORREIA",
  },
  {
    dataOrdem: "2024-06-19",
    idConsorcio: "8",
    consorcio: "STPL",
    idOperadora: "463453401",
    operadora: "******* ******* **** ********",
    idOrdemPagamento: "337",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "82773335791",
    nome: "LUCIANE PEREIRA LIMA LOUREIRO",
  },
  {
    dataOrdem: "2024-06-19",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463494930",
    operadora: "**** **** *******",
    idOrdemPagamento: "337",
    quantidadeTransacaoDebito: 3,
    valorDebito: 12.9,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 12.9,
    valorDescontoTaxa: 0.516,
    valorTotalTransacaoLiquido: 12.384,
    versao: "31a6853cb59b7bd67d2f865fa81c6992ac4e1435",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "46285911649",
    nome: "JOSE DIAS XIMENES",
  },
  {
    dataOrdem: "2024-06-20",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463494930",
    operadora: "**** **** *******",
    idOrdemPagamento: "338",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "7bcba650c069552886d5571ba3a056a9d3bf8789",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "46285911649",
    nome: "JOSE DIAS XIMENES",
  },
  {
    dataOrdem: "2024-06-20",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463413106",
    operadora: "**** *********",
    idOrdemPagamento: "338",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "7bcba650c069552886d5571ba3a056a9d3bf8789",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "79464637749",
    nome: "INES FERNANDES",
  },
  {
    dataOrdem: "2024-06-20",
    idConsorcio: "9",
    consorcio: "STPC",
    idOperadora: "463413258",
    operadora: "**** ***** ** ***********",
    idOrdemPagamento: "338",
    quantidadeTransacaoDebito: 1,
    valorDebito: 4.3,
    quantidadeTransacaoEspecie: 0,
    valorEspecie: 0,
    quantidadeTransacaoGratuidade: 0,
    valorGratuidade: 0,
    quantidadeTransacaoIntegracao: 0,
    valorIntegracao: 0,
    quantidadeTransacaoRateioCredito: 0,
    valorRateioCredito: 0,
    quantidadeTransacaoRateioDebito: 0,
    valorRateioDebito: 0,
    valorTotalTransacaoBruto: 4.3,
    valorDescontoTaxa: 0.172,
    valorTotalTransacaoLiquido: 4.128,
    versao: "7bcba650c069552886d5571ba3a056a9d3bf8789",
    operadoraTipoDocumento: "CPF",
    consorcioCnpj: null,
    operadoraCpfCnpj: "29709920782",
    nome: "JOAO SALES DE ALBUQUERQUE",
  },
];
